### PR TITLE
Added design for calculator project submission

### PR DESCRIPTION
**Pull request by Melocoder**
https://melocoder.github.io/calculator

### CODE REVIEW

**Comment by Chiagozielam** [comment]
Your PR should be descriptive of what you did in it. A better name could be: `Add design for the calculator project submission`

**Comment by Melocoder** [comment]
Changes made

**Comment by ebenezerdon** [comment]
Hi @Melocoder, can you add a link to your hosted app in the PR description?

**Comment by Melocoder** [comment]
> Hi @Melocoder, can you add a link to your hosted app in the PR description?

Hosted link added.

**Pull request closed without merging**
